test_format = 1.0

[default]

    # -------------------------------
    # Default args to use for install
    # -------------------------------
    
    args.auth_method = "ldap"

    # -------------------------------
    # Default args to use for install
    # -------------------------------
    
    exclude = ["install.nourl"]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.d653976.name = "Upgrade from 23.01"

[standard_auth_method]

    only = ["install.subdir", "backup_restore", "upgrade"]

    args.auth_method = "standard"
